import React from "react";
import Auth from "../components/Auth";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const page = () => {
  return <Auth />;
};

export default page;
